insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'ddonise0', 'Mozilla/5.0 (X11; CrOS i686 13.587.48) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.43 Safari/535.1', 'software', 'low', 14, 'Polynesian', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'jlongthorn1', 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30', 'software', 'high', 14, 'Indonesian', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'akearley2', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.724.100 Safari/534.30', 'hardware', 'low', 5, 'Cheyenne', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('open', 'dbentz3', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11', 'software', 'low', 25, 'Yakama', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('open', 'ceverington4', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.861.0 Safari/535.2', 'hardware', 'normal', 45, 'Central American', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'bbelhome5', 'Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.20 Safari/535.1', 'hardware', 'low', 48, 'Laotian', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'lhavis6', 'Mozilla/5.0 (Windows NT 7.1) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30', 'software', 'low', 26, 'Uruguayan', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('open', 'fgair7', 'Mozilla/5.0 (Windows; U; Windows NT 6.1; sv-SE) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4', 'hardware', 'normal', 17, 'Micronesian', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'dolijve8', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; zh-cn) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27', 'software', 'low', 30, 'Latin American Indian', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('open', 'tmayworth9', 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1061.1 Safari/536.3', 'hardware', 'high', 1, 'Chippewa', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('solved', 'obraveya', 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.13 (KHTML, like Gecko) Chrome/24.0.1290.1 Safari/537.13', 'hardware', 'normal', 43, 'Argentinian', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('pending', 'jdawneyb', 'Mozilla/5.0 (Windows NT 5.2; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.63 Safari/535.7', 'hardware', 'low', 8, 'Panamanian', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('open', 'bmilmoc', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.1 (KHTML, like Gecko) Ubuntu/10.10 Chromium/14.0.808.0 Chrome/14.0.808.0 Safari/535.1', 'hardware', 'high', 36, 'Korean', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('solved', 'trickmand', 'Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_7) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.790.0 Safari/535.1', 'software', 'high', 34, 'Native Hawaiian and Other Pacific Islander (NHPI)', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into ticketHardware (status, userCreator, assigneeUser, typeOfTicket, priority, position, hardwareToBeChanged, comments) values ('open', 'dbeangee', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.24 Safari/535.1', 'software', 'low', 41, 'Indonesian', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
