DROP TABLE EMPLOYEE IF EXISTS;

CREATE TABLE employee (
	employeeID INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255),
	email VARCHAR(255),
	position VARCHAR(255),
	numAssignTicks int
);

DROP TABLE USERS IF EXISTS;

CREATE TABLE users (
	userID INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255),
	email VARCHAR(255),
	numTickets int
);