package com.csis3275.test;

// Generated by Selenium IDE
import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
public class InventoryPageTestTest {
	
	private static WebDriver driver;
	private static Map<String, Object> vars;
	static JavascriptExecutor js;

	@BeforeAll
	static void setUpBeforeClass() throws Exception {

		// Setup the Chrome Driver
		
		System.setProperty("webdriver.chrome.driver", "c:\\temp\\chromedriver.exe");
		driver = new ChromeDriver();
		
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

  @AfterAll
  static void tearDownAfterClass() {
    driver.quit();
  }
  
	@BeforeEach
	void setUp() throws Exception {
	}

	@AfterEach
	void tearDown() throws Exception {
	}


	//Test update returns successfully
  @Test
  public void inventoryPageTest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1884, 1032));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("Kneale95@hotmail.ca");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Kneale95");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    
    //Test Location Change
    driver.findElement(By.cssSelector(".nav-list > li:nth-child(3) > a")).click();
    driver.findElement(By.linkText("Edit")).click();
    driver.findElement(By.id("itemLocation")).click();
    driver.findElement(By.id("itemLocation")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Edit")).click();
    driver.findElement(By.id("itemLocation")).click();
    {
      WebElement dropdown = driver.findElement(By.id("itemLocation"));
      dropdown.findElement(By.xpath("//option[. = 'Send for Repairs']")).click();
    }
    driver.findElement(By.cssSelector(".btn")).click();
    
    assertEquals("Successfully Updated Item 1", driver.findElement(By.className("alert")).getText());
  }   

}
